
// --------------- Zero Page Constants ---------------

.label ZP_ROW_LO			= ZERO_PAGE_ADDRESS + 0
.label ZP_ROW_HI			= ZERO_PAGE_ADDRESS + 1
.label ZP_ROW_COLOR_LO		= ZERO_PAGE_ADDRESS + 2
.label ZP_ROW_COLOR_HI		= ZERO_PAGE_ADDRESS + 3
.label ZP_ROOM_LO			= ZERO_PAGE_ADDRESS + 4
.label ZP_ROOM_HI			= ZERO_PAGE_ADDRESS + 5
.label ZP_ANIM_LO			= ZERO_PAGE_ADDRESS + 6
.label ZP_ANIM_HI			= ZERO_PAGE_ADDRESS + 7
.label ZP_ROOM_INFO_LO		= ZERO_PAGE_ADDRESS + 8
.label ZP_ROOM_INFO_HI		= ZERO_PAGE_ADDRESS + 9
.label ZP_SPRITE_TYPE_LO	= ZERO_PAGE_ADDRESS + 10
.label ZP_SPRITE_TYPE_HI	= ZERO_PAGE_ADDRESS + 11
.label ZP_TEXT_LO			= ZERO_PAGE_ADDRESS + 12
.label ZP_TEXT_HI			= ZERO_PAGE_ADDRESS + 13
